name: Deploy Dev

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - 'main'
      - 'releases/**'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

#      - name: Setup Golang
#        uses: actions/setup-go@v4
#        with:
#          go-version: 1.20.x

      - name: Build
        run: docker build -t olexandrho/test .

