name: Deploy Dev
on:
  - push

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

#      - name: Setup Golang
#        uses: actions/setup-go@v4
#        with:
#          go-version: 1.20.x

      - name: Build
        run: docker build -t olexandrho/test .

