name: Deploy Stage

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - 'stage'
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: docker build -t olexandrho/test .

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: List Vars @@@@@@@@@@@@@@@@@@@@@@@@@@@@
        run: |
          echo "${{ steps.branch-name.outputs.base_ref_branch }}"
          echo "${{ steps.branch-name.outputs.current_branch }}"
          echo "${{ steps.branch-name.outputs.default_branch }}"
          echo "${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "${{ steps.branch-name.outputs.is_default }}"

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: olexandrho/test
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "5454"

