name: Publish Godoc

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - 'main'
      - 'stage'
      - 'releases/**'

jobs:
  build-doc:
    runs-on: ubuntu-22.04
    name: Godoc App
    steps:
      - uses: actions/checkout@v3

      - name: Generate GoDoc
        uses: ktr0731/godoc-action@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
