name: Quality check

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - 'main'
      - 'releases/**'
    paths-ignore:
      - '**.md'

jobs:
  unit-testing:
    runs-on: ubuntu-22.04
    env:
      DUMMY_VAR: 'test'
    steps:
      - uses: actions/checkout@v3

      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Test with coverage
        run: go test ./... -coverpkg=./... -coverprofile cover.out
      - name: Clover coverage
        run: |-
          go get github.com/codeofthrone/goclover && \
          goclover -f cover.out -o clover.xml