name: Quality Check

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  push:
    branches:
      - 'main'
      - 'stage'
      - 'releases/**'
    paths-ignore:
      - '**.md'

jobs:
  formatting:
    runs-on: ubuntu-22.04
    steps:
      - name: Format
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
        if: matrix.os == 'ubuntu-latest'

  unit-testing:
    runs-on: ubuntu-22.04
    env:
      DUMMY_VAR: 'test'
    steps:
      - uses: actions/checkout@v3
      # Set up go 1.20.x
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x
      # run unit tests
      - name: Test with coverage
        run: go test ./... -coverpkg=./...

  security-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # Run Gosec Security Scanner
      - uses: ynniss/golang-security-action@v0.1.3
        with:
          CODE_PATH: "./"